/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import dao.PoliceDAO;
import dao.VehicleDAO;
import dao.DatabaseConnection;
import com.AavengersTrafficControle.trafficsystem.model.Police;
import com.AavengersTrafficControle.trafficsystem.model.Person;
import com.AavengersTrafficControle.trafficsystem.model.Vehicle;
import com.AavengersTrafficControle.trafficsystem.model.Report;
import java.sql.Connection;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author moham
 */
public class GUIAPP extends javax.swing.JFrame {

    private final PoliceDAO policeDAO;
    private final VehicleDAO vehicleDAO = new VehicleDAO();
    private java.util.function.Consumer<Police> onLoginSuccess;

    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JButton searchVehicleButton;
    private javax.swing.JButton searchPersonButton;
    private javax.swing.JButton createReportButton;
    private javax.swing.JButton viewMyReportsButton;
    private javax.swing.JButton viewAllReportsButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel backgroundLabel;

    /**
     * Creates new form GUIAPP
     */
    public GUIAPP() {
        Connection connection = DatabaseConnection.getConnection();
        this.policeDAO = new PoliceDAO(connection);
        setBackgroundImage(); // Set background before initializing components
        initComponents();
    }

    private void setBackgroundImage() {
        try {
            javax.swing.ImageIcon bgIcon = new javax.swing.ImageIcon(getClass().getResource("/background.png"));
            backgroundLabel = new javax.swing.JLabel(bgIcon);
            backgroundLabel.setBounds(0, 0, bgIcon.getIconWidth(), bgIcon.getIconHeight());
            // Create the layered pane if not already created
            if (TrafficSystem == null) {
                TrafficSystem = new javax.swing.JLayeredPane();
            }
            TrafficSystem.setPreferredSize(new java.awt.Dimension(bgIcon.getIconWidth(), bgIcon.getIconHeight()));
            TrafficSystem.add(backgroundLabel, Integer.valueOf(Integer.MIN_VALUE));
            TrafficSystem.setLayer(backgroundLabel, Integer.MIN_VALUE);
            // Set frame size to image size
            setSize(bgIcon.getIconWidth(), bgIcon.getIconHeight());
            setMinimumSize(new java.awt.Dimension(bgIcon.getIconWidth(), bgIcon.getIconHeight()));
        } catch (Exception e) {
            System.err.println("Background image not found: " + e.getMessage());
        }
    }

    public void setOnLoginSuccess(java.util.function.Consumer<Police> onLoginSuccess) {
        this.onLoginSuccess = onLoginSuccess;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TrafficSystem = new javax.swing.JLayeredPane();
        loginPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traffic System Login");

        // Main panel styling
        TrafficSystem.setBackground(new java.awt.Color(245, 245, 245));
        TrafficSystem.setOpaque(true);

        // Login panel styling
        loginPanel.setOpaque(true);
        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220), 1, true),
            javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30)
        ));
        java.awt.GridBagLayout gbl = new java.awt.GridBagLayout();
        loginPanel.setLayout(gbl);
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 1; gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(0, 0, 15, 0);

        // Title label
        titleLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 32));
        titleLabel.setForeground(new java.awt.Color(33, 150, 243));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Welcome to the Traffic System");
        loginPanel.add(titleLabel, gbc);

        // Subtitle label
        gbc.gridy++;
        subtitleLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        subtitleLabel.setForeground(new java.awt.Color(100, 100, 100));
        subtitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitleLabel.setText("Please log in to continue");
        loginPanel.add(subtitleLabel, gbc);

        // Username field
        gbc.gridy++;
        jTextField1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 2, true),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        jTextField1.setToolTipText("Username");
        jTextField1.setPreferredSize(new java.awt.Dimension(250, 40));
        loginPanel.add(jTextField1, gbc);

        // Password field
        gbc.gridy++;
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 2, true),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        jPasswordField1.setToolTipText("Password");
        jPasswordField1.setPreferredSize(new java.awt.Dimension(250, 40));
        loginPanel.add(jPasswordField1, gbc);

        // Login button
        gbc.gridy++;
        jButton1.setBackground(new java.awt.Color(33, 150, 243));
        jButton1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        jButton1.setForeground(java.awt.Color.WHITE);
        jButton1.setText("Log In");
        jButton1.setFocusPainted(false);
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(250, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginPanel.add(jButton1, gbc);

        // Center the login panel in the layered pane
        TrafficSystem.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints centerGbc = new java.awt.GridBagConstraints();
        centerGbc.gridx = 0; centerGbc.gridy = 0;
        centerGbc.anchor = java.awt.GridBagConstraints.CENTER;
        TrafficSystem.add(loginPanel, centerGbc);

        // Set the main frame layout
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(TrafficSystem, java.awt.BorderLayout.CENTER);

        pack();
        setMinimumSize(new java.awt.Dimension(400, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = jTextField1.getText().trim();
        String password = new String(jPasswordField1.getPassword()).trim();

        Police user = policeDAO.authenticate(username, password);
        if (user != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Login successful!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            if (onLoginSuccess != null) {
                onLoginSuccess.accept(user);
            }
            initMainMenuPanel();
            TrafficSystem.remove(loginPanel); // Remove the login panel
            TrafficSystem.add(mainMenuPanel); // Add the main menu panel
            TrafficSystem.revalidate(); // Refresh the layout
            TrafficSystem.repaint(); // Repaint the container
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid username or password.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void initMainMenuPanel() {
        mainMenuPanel = new javax.swing.JPanel();
        mainMenuPanel.setLayout(new java.awt.GridLayout(7, 1, 15, 15));
        mainMenuPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainMenuPanel.setBackground(new java.awt.Color(240, 240, 240));

        searchVehicleButton = createStyledButton("Search Vehicle by Plate Number");
        searchPersonButton = createStyledButton("Search Person by National ID");
        createReportButton = createStyledButton("Create New Report");
        viewMyReportsButton = createStyledButton("View My Reports");
        viewAllReportsButton = createStyledButton("View All Reports");
        logoutButton = createStyledButton("Logout");
        javax.swing.JButton payReportFeesButton = createStyledButton("Pay Report Fees");

        searchVehicleButton.addActionListener(evt -> searchVehicleByPlate());
        searchPersonButton.addActionListener(evt -> searchPersonByNationalId());
        createReportButton.addActionListener(evt -> createNewReport());
        viewMyReportsButton.addActionListener(evt -> viewMyReports());
        viewAllReportsButton.addActionListener(evt -> viewAllReports());
        logoutButton.addActionListener(evt -> logout());
        payReportFeesButton.addActionListener(evt -> showPayWindow());

        mainMenuPanel.add(searchVehicleButton);
        mainMenuPanel.add(searchPersonButton);
        mainMenuPanel.add(createReportButton);
        mainMenuPanel.add(viewMyReportsButton);
        mainMenuPanel.add(viewAllReportsButton);
        mainMenuPanel.add(payReportFeesButton);
        mainMenuPanel.add(logoutButton);

        getContentPane().add(mainMenuPanel, java.awt.BorderLayout.CENTER);
    }

    private javax.swing.JButton createStyledButton(String text) {
        javax.swing.JButton button = new javax.swing.JButton(text);
        button.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        button.setBackground(new java.awt.Color(33, 150, 243));
        button.setForeground(java.awt.Color.WHITE);
        button.setFocusPainted(false);
        button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        return button;
    }

    private void showStyledMessageDialog(String message, String title, int messageType) {
        javax.swing.UIManager.put("OptionPane.messageFont", new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        javax.swing.UIManager.put("OptionPane.buttonFont", new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        javax.swing.JOptionPane.showMessageDialog(this, message, title, messageType);
    }

    private int showStyledConfirmDialog(javax.swing.JPanel panel, String title) {
        javax.swing.UIManager.put("OptionPane.messageFont", new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        javax.swing.UIManager.put("OptionPane.buttonFont", new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        return javax.swing.JOptionPane.showConfirmDialog(this, panel, title, javax.swing.JOptionPane.OK_CANCEL_OPTION);
    }

    private void searchVehicleByPlate() {
        String plateNumber = javax.swing.JOptionPane.showInputDialog(this, "Enter plate number:");
        if (plateNumber != null) {
            List<Vehicle> vehicles = vehicleDAO.findByPlateNumber(plateNumber);
            if (!vehicles.isEmpty()) {
                StringBuilder result = new StringBuilder("<html><body style='font-family:Segoe UI; font-size:14px;'>");
                result.append("<h3>Vehicles Found:</h3><table border='1' style='border-collapse:collapse; width:100%;'>");
                result.append("<tr><th>Plate Number</th><th>Owner Name</th><th>Owner National ID</th><th>Car Type</th><th>Color</th><th>Model</th><th>Year</th><th>Reports</th></tr>");
                for (Vehicle v : vehicles) {
                    String ownerName = policeDAO.getOwnerNameById(v.getOwnerId()); // Fetch owner name
                    String ownerNationalId = policeDAO.getOwnerNationalIdById(v.getOwnerId()); // Fetch owner national ID
                    List<Report> reports = policeDAO.getReportsByVehicleId(v.getVehicleId()); // Fetch reports
                    String reportStatus;
                    String reportColor;
                    if (reports.isEmpty()) {
                        reportStatus = "No Reports";
                        reportColor = "green";
                    } else {
                        reportStatus = "Has Reports";
                        reportColor = "red";
                    }
                    result.append("<tr>")
                          .append("<td>").append(v.getPlateNumber()).append("</td>")
                          .append("<td>").append(ownerName).append("</td>")
                          .append("<td>").append(ownerNationalId).append("</td>")
                          .append("<td>").append(v.getType()).append("</td>")
                          .append("<td>").append(v.getColor()).append("</td>")
                          .append("<td>").append(v.getModel()).append("</td>")
                          .append("<td>").append(v.getYear()).append("</td>")
                          .append("<td style='color:").append(reportColor).append(";'>").append(reportStatus).append("</td>")
                          .append("</tr>");
                }
                result.append("</table></body></html>");
                javax.swing.JLabel resultLabel = new javax.swing.JLabel(result.toString());
                resultLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
                javax.swing.JOptionPane.showMessageDialog(this, resultLabel, "Search Results", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                showStyledMessageDialog("No vehicles found with that plate number.", "Search Results", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    private void searchPersonByNationalId() {
        String nationalId = javax.swing.JOptionPane.showInputDialog(this, "Enter national ID:");
        if (nationalId != null) {
            Object result = policeDAO.findPersonByNationalId(nationalId);
            if (result != null && result instanceof Person) {
                Person person = (Person) result;
                List<Report> reports = policeDAO.getReportsByPersonId(person.getPersonId()); // Fetch reports

                StringBuilder resultBuilder = new StringBuilder("<html><body style='font-family:Segoe UI; font-size:14px;'>");
                resultBuilder.append("<h3>Person Details:</h3>")
                             .append("<p>Name: ").append(person.getName()).append("</p>")
                             .append("<p>National ID: ").append(person.getNationalId()).append("</p>")
                             .append("<p>Address: ").append(person.getAddress()).append("</p>");

                resultBuilder.append("<h3>Associated Reports:</h3>")
                             .append("<table border='1' style='border-collapse:collapse; width:100%;'>")
                             .append("<tr><th>Report ID</th><th>Violation Type</th><th>Status</th></tr>");

                for (Report report : reports) {
                    String reportColor = report.getStatus().equalsIgnoreCase("No Reports") ? "green" : "red";
                    String paymentStatus = report.isPaid() ? "Paid" : "Pending";
                    resultBuilder.append("<tr>")
                                 .append("<td>").append(report.getReportId()).append("</td>")
                                 .append("<td>").append(report.getViolationType()).append("</td>")
                                 .append("<td style='color:").append(reportColor).append(";'>").append(report.getStatus()).append(" (" + paymentStatus + ")").append("</td>")
                                 .append("</tr>");
                }

                resultBuilder.append("</table></body></html>");

                javax.swing.JLabel resultLabel = new javax.swing.JLabel(resultBuilder.toString());
                resultLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
                javax.swing.JOptionPane.showMessageDialog(this, resultLabel, "Search Results", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                showStyledMessageDialog("No person found with that national ID.", "Search Results", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    private void createNewReport() {
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(9, 2, 10, 10));
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        javax.swing.JTextField driverIdField = new javax.swing.JTextField();
        javax.swing.JTextField vehicleIdField = new javax.swing.JTextField();
        javax.swing.JTextField violationTypeField = new javax.swing.JTextField();
        javax.swing.JTextField locationField = new javax.swing.JTextField();
        javax.swing.JTextField descriptionField = new javax.swing.JTextField();
        javax.swing.JTextField fineField = new javax.swing.JTextField();
        javax.swing.JTextField pointsField = new javax.swing.JTextField();
        javax.swing.JComboBox<String> reportTypeComboBox = new javax.swing.JComboBox<>(new String[]{"Regular", "Stolen", "Lost"});

        panel.add(new javax.swing.JLabel("Driver ID:"));
        panel.add(driverIdField);
        panel.add(new javax.swing.JLabel("Vehicle ID:"));
        panel.add(vehicleIdField);
        panel.add(new javax.swing.JLabel("Violation Type:"));
        panel.add(violationTypeField);
        panel.add(new javax.swing.JLabel("Location:"));
        panel.add(locationField);
        panel.add(new javax.swing.JLabel("Description:"));
        panel.add(descriptionField);
        panel.add(new javax.swing.JLabel("Fine Amount:"));
        panel.add(fineField);
        panel.add(new javax.swing.JLabel("Points to Deduct:"));
        panel.add(pointsField);
        panel.add(new javax.swing.JLabel("Report Type:"));
        panel.add(reportTypeComboBox);

        int result = showStyledConfirmDialog(panel, "Create New Report");
        if (result == javax.swing.JOptionPane.OK_OPTION) {
            try {
                int driverId = Integer.parseInt(driverIdField.getText().trim());
                int vehicleId = Integer.parseInt(vehicleIdField.getText().trim());
                String violationType = violationTypeField.getText().trim();
                String location = locationField.getText().trim();
                String description = descriptionField.getText().trim();
                double fine = Double.parseDouble(fineField.getText().trim());
                int points = Integer.parseInt(pointsField.getText().trim());
                String reportType = (String) reportTypeComboBox.getSelectedItem();

                if (violationType.isEmpty() || location.isEmpty() || description.isEmpty()) {
                    throw new IllegalArgumentException("All text fields must be filled.");
                }

                String confirmationMessage = String.format(
                    "<html><body style='font-family:Segoe UI; font-size:14px;'>"+
                    "<h3>Confirm Report Details:</h3>"+
                    "<p>Driver ID: %d</p>"+
                    "<p>Vehicle ID: %d</p>"+
                    "<p>Violation Type: %s</p>"+
                    "<p>Location: %s</p>"+
                    "<p>Description: %s</p>"+
                    "<p>Fine Amount: %.2f</p>"+
                    "<p>Points to Deduct: %d</p>"+
                    "<p>Report Type: %s</p>"+
                    "</body></html>",
                    driverId, vehicleId, violationType, location, description, fine, points, reportType
                );

                int confirm = javax.swing.JOptionPane.showConfirmDialog(this, new javax.swing.JLabel(confirmationMessage), "Confirm Report", javax.swing.JOptionPane.OK_CANCEL_OPTION);
                if (confirm == javax.swing.JOptionPane.OK_OPTION) {
                    Report report = new Report();
                    report.setPoliceId(1); // Replace with the actual police ID
                    report.setDriverId(driverId);
                    report.setVehicleId(vehicleId);
                    report.setViolationType(violationType);
                    report.setLocation(location);
                    report.setDescription(description);
                    report.setFine(fine);
                    report.setPointsDeducted(points);
                    report.setReportDate(new java.util.Date());
                    report.setStatus("Pending");
                    report.setPaid(false);
                    report.setReportType(reportType); // New field for report type
                    report.setDueDate(new java.util.Date()); // Set the due date to the current date

                    if (policeDAO.createReport(report)) {
                        showStyledMessageDialog("Report created successfully.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        showStyledMessageDialog("Failed to create report.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (NumberFormatException e) {
                showStyledMessageDialog("Invalid input. Please enter valid numbers for Driver ID, Vehicle ID, Fine, and Points.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            } catch (IllegalArgumentException e) {
                showStyledMessageDialog(e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void viewMyReports() {
        try {
            List<Report> reports = policeDAO.getReportsByPoliceId(1); // Replace with the actual police ID
            if (reports != null && !reports.isEmpty()) {
                StringBuilder result = new StringBuilder("Your Reports:\n\n");
                for (Report report : reports) {
                    result.append(report.toString()).append("\n\n");
                }
                javax.swing.JOptionPane.showMessageDialog(this, result.toString(), "My Reports", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No reports found.", "My Reports", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "An error occurred while fetching reports: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void viewAllReports() {
        List<Report> reports = policeDAO.getAllReports();
        if (!reports.isEmpty()) {
            StringBuilder result = new StringBuilder("<html><body style='font-family:Segoe UI; font-size:14px;'>");
            result.append("<h3>All Reports:</h3><table border='1' style='border-collapse:collapse; width:100%;'>");
            result.append("<tr><th>Report ID</th><th>Driver ID</th><th>Vehicle ID</th><th>Violation Type</th><th>Status</th><th>Fine</th><th>Points Deducted</th><th>Report Date</th></tr>");

            for (Report report : reports) {
                String statusColor = report.getStatus().equalsIgnoreCase("Pending") ? "orange" : "green";
                result.append("<tr>")
                      .append("<td>").append(report.getReportId()).append("</td>")
                      .append("<td>").append(report.getDriverId()).append("</td>")
                      .append("<td>").append(report.getVehicleId()).append("</td>")
                      .append("<td>").append(report.getViolationType()).append("</td>")
                      .append("<td style='color:").append(statusColor).append(";'>").append(report.getStatus()).append("</td>")
                      .append("<td>").append(report.getFine()).append("</td>")
                      .append("<td>").append(report.getPointsDeducted()).append("</td>")
                      .append("<td>").append(report.getReportDate()).append("</td>")
                      .append("</tr>");
            }

            result.append("</table></body></html>");
            javax.swing.JLabel resultLabel = new javax.swing.JLabel(result.toString());
            resultLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
            javax.swing.JOptionPane.showMessageDialog(this, resultLabel, "All Reports", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No reports found.", "All Reports", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }

    private void payReportFees() {
        String reportIdInput = javax.swing.JOptionPane.showInputDialog(this, "Enter Report ID to pay fees:");
        if (reportIdInput != null) {
            try {
                int reportId = Integer.parseInt(reportIdInput.trim());

                int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to pay the fees for Report ID: " + reportId + "?",
                    "Confirm Payment",
                    javax.swing.JOptionPane.OK_CANCEL_OPTION);

                if (confirm == javax.swing.JOptionPane.OK_OPTION) {
                    boolean success = policeDAO.payReportFees(reportId);
                    if (success) {
                        showStyledMessageDialog("Payment successful for Report ID: " + reportId, "Payment Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        showStyledMessageDialog("Failed to process payment. Please check the Report ID.", "Payment Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (NumberFormatException e) {
                showStyledMessageDialog("Invalid Report ID. Please enter a valid number.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void showPayWindow() {
        JFrame frame = new JFrame("Pay Report Fees");
        frame.setSize(500, 300);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setResizable(true);

        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout(10, 10));
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));

        JLabel titleLabel = new JLabel("Pay Report Fees", JLabel.CENTER);
        titleLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        titleLabel.setForeground(new java.awt.Color(33, 150, 243));
        panel.add(titleLabel, BorderLayout.NORTH);

        JPanel formPanel = new JPanel(new GridLayout(2, 2, 10, 10));

        JLabel selectLabel = new JLabel("Select Report ID:");
        selectLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        formPanel.add(selectLabel);

        JComboBox<Integer> reportDropdown = new JComboBox<>();
        List<Integer> unpaidReportIds = policeDAO.getUnpaidReportIds(); // Fetch unpaid report IDs from the database
        for (Integer id : unpaidReportIds) {
            reportDropdown.addItem(id);
        }
        reportDropdown.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        formPanel.add(reportDropdown);

        panel.add(formPanel, BorderLayout.CENTER);

        JButton payButton = new JButton("Pay");
        payButton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        payButton.setBackground(new java.awt.Color(33, 150, 243));
        payButton.setForeground(java.awt.Color.WHITE);
        payButton.setFocusPainted(false);
        payButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payButton.addActionListener(e -> {
            Integer selectedReportId = (Integer) reportDropdown.getSelectedItem();
            if (selectedReportId != null) {
                boolean success = policeDAO.payReportFees(selectedReportId);
                if (success) {
                    JOptionPane.showMessageDialog(frame, "Payment successful for Report ID: " + selectedReportId, "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(frame, "Payment failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        JPanel buttonPanel = new JPanel();
        buttonPanel.add(payButton);
        panel.add(buttonPanel, BorderLayout.SOUTH);

        frame.add(panel);
        frame.setLocationRelativeTo(null); // Center the window on the screen
        frame.setVisible(true);
    }

    private void logout() {
        // Implementation for logout
        javax.swing.JOptionPane.showMessageDialog(this, "Logging out...");
        this.dispose();
        new GUIAPP().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane TrafficSystem;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JPanel loginPanel;
    // End of variables declaration//GEN-END:variables
}
